# Change these first
owner: awesomebible # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: awesomebible.de
    url: https://awesomebible.de
  - name: en.awesomebible.de
    url: https://en.awesomebible.de
  - name: awesomeBible Docs
    url: https://docs.awesomebible.de
  - name: verse.awesomebible.de
    url: https://verse.awesomebible.de
  - name: versepicker.awesomebible.de
    url: https://versepicker.awesomebible.de
  - name: my.awesomebible.de
    url: https://my.awesomebible.de
  - name: Kinde Auth
    url: https://auth.awesomebible.de
  - name: Losungen (Daily Texts)
    url: https://losungen.awesomebible.de
  - name: OpenBibleProject
    url: https://obp.awesomebible.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.awesomebible.de
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.jsdelivr.net/gh/awesomebible/assets@3b6cdf5/svgs/logomark-white.svg
  name: Status
  introTitle: "Status of awesomeBible websites and services"
  introMessage: "The status of the website is checked every 5 minutes. If something goes wrong and isn't reflected here, feel free to [contact us](mailto:hey@awesomebible.de)!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
